### ISSUE TITLE
[Remoto] Flutter Developer na i10digital

### ISSUE THREAD

**Issue by carol-monteiro** [Flutter-Brazil/vagas#12]
## Descrição da vaga

Procuramos um(a) desenvolvedor(a) de Mobile com experiência em Flutter, que goste de desafios e de resolver problemas. O candidato vai compor o time de desenvolvimento da nossa plataforma de WebBanking para empresas. 

## Local

Remoto

## Benefícios e Diferenciais

- Remuneração competitiva
- Final de semana de 3 dias
- Autonomia na escolha de horário de trabalho 

## Requisitos

**Obrigatórios:**
- Já ter trabalho na prática com Flutter

**Desejáveis:**
- 

**Diferenciais:**
- React
- PHP e/ou Node

## Contratação

PJ 

## Nossa empresa

A i10 é um banco digital focado em empresas que traz soluções financeiras direto para a plataforma do cliente. Queremos pessoas que tenham a ambição de crescer junto com a gente, em um ambiente de aprendizagem e dedicação.

## Como se candidatar

Por favor envie um email para carol@i10digital.com.br com seu CV anexado e Linkedin - enviar no assunto: Vaga Flutter

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 3k-5k

**Comment by gutosoares** [comment]
Oi @carolina-am eu enviei um email no dia 22/01 e não obtive resposta. Essa vaga ainda está aberta?

**Comment by carolina-am** [comment]
Oi Augusto, tudo bem?
Esse é meu email pessoal entao geralmente demoro para responder quando sao outros assuntos.
Sim, a vaga está aberta, assim como consta no GitHub, e estamos selecionando alguns dos candidatos.
Mas as entrevistas nao serao por agora, estamos montando o banco de candidatos primeiro e analisando todos pelo currículo para selecionar os que irao para as entrevistas.
Para Flutter, inclusive, estamos nos adaptando com um dev agora e daqui há um mes possivelmente, ou um pouco menos, que vamos iniciar as entrevistas novamente.
Entao assim que começar, entro em contato. Só esperar =)

Obrigada.

Att,

--
Carolina Monteiro


________________________________
De: Augusto Soares Pereira <notifications@github.com>
Enviado: sábado, 8 de fevereiro de 2020 21:54
Para: Flutter-Brazil/vagas <vagas@noreply.github.com>
Cc: Carol Monteiro <carolina.am@outlook.com>; Mention <mention@noreply.github.com>
Assunto: Re: [Flutter-Brazil/vagas] [Remoto] Flutter Developer na i10digital (#12)


Oi @carolina-am<https://github.com/carolina-am> eu enviei um email no dia 22/01 e não obtive resposta. Essa vaga ainda está aberta?

**Comment by jeaanlucas** [comment]
Acabei de enviar um e-mail para você @carolina-am

**Comment by tigosante** [comment]
Tem possibilidade de trabalho remoto?
