### ISSUE TITLE
[São Paulo] Flutter Developer Freela de 6 meses [Empresa em desenvolvimento]. 

### ISSUE THREAD

**Issue by Wellingtonpereira** [Flutter-Brazil/vagas#18]
Olá galera, tudo bem?

Estou procurando um Dev de Flutter para iniciar um projeto, o tempo de desenvolvimento vai depender da capacidade do dev, mas, inicialmente esta para 6 meses.

A tarefa será desenvolver o app desde a camada de autenticação, até alguns simples relatórios dentro do app/web.

Interessados, por favor só deixar uma interação nesse post q eu entro em contato.

Ah, o modelo de trabalho que procuro pode ser por: valor da hora ou parcerias, depende muito da forma que você se sentir confortável.

Obrigado por ler esse pequeno texto. 😀

**Comment by fabianogadenz** [comment]
gostaria de receber mais informações @Wellingtonpereira. fabianomgadenz@gmail.com

**Comment by rafapil** [comment]
@Wellingtonpereira remoto?

**Comment by LucasS03** [comment]
@Wellingtonpereira é remoto?

**Comment by WilliamCunhaCardoso** [comment]
remoto? qts horas por dia? e qual o nível? jr, pleno ou sr?

**Comment by FelipeQueFez** [comment]
@Wellingtonpereira gostaria de saber um pouco mais !

**Comment by Wellingtonpereira** [comment]
E ai Galera, desculpem a demora, podem me chamar no whats? 14 996376294

**Comment by Wellingtonpereira** [comment]
Obrigado pelos interessados. vaga preenchida.
