### ISSUE TITLE
[REMOTO] Flutter Developer na SNAPFI

### ISSUE THREAD

**Issue by marcelinobadin** [Flutter-Brazil/vagas#280]
## Descrição da vaga

Procuramos pessoas engenheiras de software (mobile) que nos ajudem a transformar esse sonho em produto.

## Local

Remoto

## Nossa Empresa

[Snapfi](https://www.linkedin.com/company/snap-fi/)

A Snapfi nasce com um propósito: tornar-se a principal parceira dos micro e pequenos empreendedores no Brasil. Hoje são mais de 40 milhões de brasileiros que batalham duro, diariamente, para administrar seus negócios. A Snapfi vem para descomplicar a gestão financeira para esses empreendedores e ajudá-los a sonhar cada vez mais alto.

Vem fazer parte do time de fundadores de uma fintech que vem para transformar esse mercado tão importante para o desenvolvimento econômico do país. A Snapfi é o lugar certo para quem quer fazer a diferença.

## Requisitos

Nesta posição, você será responsável por:

- Participar ativamente desde a concepção de produtos e serviços, até sua entrega final, bem como suportar a sua operação em produção;
- Somos uma product company, focada na velocidade com entregas pequenas e incrementais;
- Colocar a mão na massa, desenvolvendo, revisando, testando, e fazendo troubleshooting do nosso aplicativo mobile nas plataformas Android e iOS;
- Ajudar a mentorar e desenvolver outras pessoas desenvolvedoras do time, através de revisão de código e pair programing.

Requisitos

- Buscamos perfis T-shaped. As pessoas engenheiras da Snapfi resolvem problemas com software e não se limitam à tecnologias ou limites arquiteturais de software (front end, back end, infraestrutura, etc);
- Nosso stack busca garantir um codebase único para diferentes plataformas (ex: Flutter para não ter códigos nativos iOS e Android)
- É necessário o uso extensivo de serviços de configuração que ajudem a segmentar e permitir testes A/B (ex: server driven UI);
- A solução tem como requisitos fortes: segurança, observabilidade, performance, e mantenabilidade.

## Contratação

PJ a combinar

## Como se candidatar

[Via LinkedIn](https://www.linkedin.com/jobs/view/3318661038)

## Labels

- PJ
- Remoto
- Sênior

**Comment by margotpaon** [comment]
Olá @marcelinobadin  segue meu IN: https://www.linkedin.com/in/margotpaon/
