### ISSUE TITLE
[Belo Horizonte] Flutter Developer na Zummit Tecnologia

### ISSUE THREAD

**Issue by GabrielaMartinsZummit** [Flutter-Brazil/vagas#282]
Atividades a serem desenvolvidas:
Atuação com desenvolvimento Mobile/Web responsive em Flutter; Integração com Firebase Cloud Messaging; Definição arquitetural de implementações; Integração com a API REST e construção de serviços REST baseado em micros serviços. Participar da implementação e manutenção do nosso e-commerce; Atuar na construção de soluções MVP com time multidisciplinar em um dos nossos squads. Desejável conhecimento PHP POO no Framework Laravel.
1 ano de Experiência em desenvolvimento Mobile/Web responsive em Flutter Entendimento da arquitetura de desenvolvimento

Modelo de contratação: Híbrido

Salário:
Qual sua pretensão salarial?

Benefícios:
Assistência médica
Assistência odontológica
Auxílio educação
Trabalho remoto
Vale-refeição

Caso tenha interesse, me envie seu currículo com um pouco mais de informações para:

gabriela.pereira@zummit.com.br
whatsapp: 31 995760342

Aguardo seu retorno,
Desde já agradeço,

## Labels

- Hibrido
- CLT
- Júnior
- PJ

**Comment by DaianeMGouvea** [comment]
Ser for full home office, eu me interesso

**Comment by Franciscof11** [comment]
> Ser for full home office, eu me interesso
Acho que não... Eu mandei email perguntando e nunca responderam.
