### ISSUE TITLE
[São Paulo - Remoto] Flutter Developer na Vitat | Vaga para pessoas negras

### ISSUE THREAD

**Issue by emanuel-braz** [Flutter-Brazil/vagas#286]
## Descrição da vaga

Quer trabalhar por um grande propósito? Então, que tal começar pela saúde e qualidade de vida do país inteiro? 💚🚀

Você será responsável por nos ajudar a construir a versão mobile da plataforma de saúde, trabalhando ativamente com o time de produtos para definição de tarefas.

## Local

A vaga é 100% Remoto, mas caso prefira trabalhar presencialmente, nosso escritório fica em São Paulo.

## Benefícios

- PPR - Participação nos Resultados;
- Day off de aniversário;
- Auxílio Home Office;
- Vale Refeição com saldo flexível;
- Assistência Médica;
- Assistência Odontológica;
- Seguro de Vida;
- Gympass;
- Acesso Premium a todos nosso Apps - Saúde e bem-estar é com a gente!
- Consultas liberadas com Nutricionistas, Psicólogos e Educadores Físicos em nossos apps;
- Desconto em Farmácias;
- Sócio Clube Sesc;

#### Diferenciais

- Plataforma de cursos de idiomas liberada para o colaborador;
- Política de bonificação pra indicações.
- Política de subsídio de cursos e treinamentos para turbinar o seu PDI;
- Macbook da empresa para codar sem travamentos 💙

## Requisitos

- Experiência com projetos em Flutter;
- Experiência em realizar testes de unidade e Code Review;
- Experiência com boas práticas de desenvolvimento, princípios, e design patterns;
- Experiência com os packages bloc e flutter_bloc ou outra solução de State Management;
- Experiência e entendimento sobre API, HTTP e REST;
- Experiência com git e Git Flow;
- Experiência/conhecimento de Clean Architecture.

**Diferenciais:**
- Trabalhar com metodologias ágeis de desenvolvimento de software;
- Experiência com Firebase;
- Experiência com desenvolvimento orientado a packages;
- Conhecimento com desenvolvimento nativo (Kotlin / Swift).

## Contratação

- CLT

## Nossa empresa

Nascemos para ajudar na jornada rumo a uma vida mais saudável. Vitat tem serviços, produtos e conteúdos com informações confiáveis e orientações de especialistas. Agendamentos de consultas online, marcação de exames, podcast, portal de conteúdo, programas de alimentação, movimento, autocuidado, equilíbrio e sono são algumas de nossas ferramentas.

## Como se candidatar

✨ Por favor envie um email com seu CV anexado para [emanuel.junior@vitat.com.br](mailto:emanuel.junior@vitat.com.br) com cópia [caroline.araujo@vitat.com.br](mailto:caroline.araujo@vitat.com.br)

 - Enviar no assunto: `Vaga Flutter`

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: [emanuel.junior@vitat.com.br](mailto:emanuel.junior@vitat.com.br)

## Labels

- CLT
- Júnior
- Pleno
- Remoto

**Comment by Franciscof11** [comment]
A vaga é exclusivamente para pessoas negras ou é questão de prioridade? Gostaria de me candidatar, porém não sou negro.

**Comment by emanuel-braz** [comment]
Oi @Franciscof11 esta vaga afirmativa é exclusiva para pessoas negras. Se rolar outra oportunidade, sem restrição, eu aviso por aqui tbm!  🤜🤛

**Comment by Franciscof11** [comment]
Tudo bem :)

**Comment by MoacirSchmidt** [comment]
A caracteristica mais importante para se candidatar a esta vaga é ser negro?

**Comment by WilliamCunhaCardoso** [comment]
> A caracteristica mais importante para se candidatar a esta vaga é ser negro?

Como podes ler, existem vários requisitos para a vaga. E, por ser uma vaga por diversidade, é um requisito também ser uma pessoa negra. A issue está muito bem escrita, maiores dúvidas só ler novamente mesmo.

**Comment by MoacirSchmidt** [comment]
Parabéns! Voce está ajudando a tornar o mundo um lugar muito mais inclusivo!
