### ISSUE TITLE
[REMOTO] Flutter Developer na Popcode para projeto inovador

### ISSUE THREAD

**Issue by hdoria** [Flutter-Brazil/vagas#29]
## Descrição da vaga

A [Popcode](https://www.popcode.com.br) é uma empresa especializada no desenvolvimento de aplicativos para iOS e Android. Recentemente passamos a utilizar flutter em todos os projetos. No momento, estamos com duas vagas para flutter developer, em projetos do ramo financeiro (app bancário).

## Local
Remoto

#### Diferenciais
- Homeoffice
- Alta probabilidade de crescimento
- Projeto inovador em seu seguimento
- 2 horas de almoço

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com Flutter
- 2 anos de experiência com desenvolvimento mobile

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para [queroser@popcode.com.br](mailto:queroser@popcode.com.br) com seu CV anexado e um texto de introdução no corpo do email. Enviar no assunto: Vaga Dev Flutter - Pleno/Senior

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta:  [queroser@popcode.com.br](mailto:queroser@popcode.com.br) 

## Labels

- Freela
- Júnior
- PJ
- Pleno
- Remoto
- Sênior

**Comment by mateusfccp** [comment]
Bom dia, uma dúvida.

Me parece meio contraditório haver regime de PJ e 2h de almoço, já que PJ não tem vínculo empregatício e, portanto, não está sujeito a questões de horário...

Como funciona isso?

**Comment by hdoria** [comment]
@mateusfccp Apesar do regime ser PJ, a gente trabalha remoto em horário comercial. Em 2020 queremos migrar toda a empresa para uma comunicação assíncrona e que cada um possa trabalhar no horário que quiser, desde que as metas da sprint sejam batidas. Entretanto, no momento, seguimos com horário comercial.

**Comment by thoffart** [comment]
Outra dúvida, foi aberta também outra vaga idêntica (https://github.com/react-brasil/vagas/issues/662) mas apenas trocando Flutter por React Native em um intervalo de 2 dias, no fim das contas, a empresa esta utilizando Flutter ou React Native?

**Comment by hdoria** [comment]
Fala @thoffart , tudo bom? Nós temos 3 núcleos na Popcode: 

Usávamos apenas desenvolvimento nativo até 2018 e até hoje mantemos um time dedicado a manter e adicionar recursos nos nossos projetos nativos.

Em 2018 montamos nosso time react native, que hoje é o maior, tanto em número de pessoas, quanto em quantidade de projetos. Temos diversos apps escritos e estamos planenjando mais 3-4 novos para 2020 ainda. Nosso principal projeto em react para este ano envolve a parte de de conta de pagamento, lojistas e cartão de crédito.

Em meados de 2019 começamos nosso time Flutter, que hoje está crescendo bastante e é uma de nossas apostas. Atualmente temos 11 desenvolvedores nesse time. Estamos fazendo um app bancário inteiramente em flutter e estamos começando uma espécie de concorrente para o Hotmart também usamos a tecnologia.

Sabemos que podíamos ter misturado Nativo/React/Flutter nos projetos, mas decidimos não fazer isso. Ou seja, temos times separados, criando e mantendo projetos diferentes, sem misturar as tecnologias.

**Comment by rodrigobastosv** [comment]
Boa tarde. Esta vaga ainda está ativa?
