### ISSUE TITLE
[REMOTO] Flutter Developer Estágio/JR na Athletic Gear

### ISSUE THREAD

**Issue by athletic-gear** [Flutter-Brazil/vagas#295]
## Descrição da vaga

Projeto já em funcionamento, precisamos de alguém para continuar e dar continuidade nas novas features.
Um servidor API Rest em Dart com 2 aplicativos em Flutter (Android, iOS e Web).

## Local

100% Remoto

#### Diferenciais

- Vamos ajudar você a aprender diversas tecnologias

## Requisitos

**Obrigatórios:**
- Vontade de aprender
- Dart / Flutter
- Git

**Desejáveis:**
- API Rest
- Docker
- SQL

## Contratação

A Combinar

## Como se candidatar

[Preencher o formulário](https://docs.google.com/forms/d/e/1FAIpQLSdnUz_Sd5cBCr72-iAjymAk0jHsUgm2YKTnfArnnfK91bimfA/viewform)

## Tempo médio de feedbacks

Vamos enviar o feedback e fazer as entrevistas durante o mês de Junho.

## Labels

- Estágio
- Júnior
- Remoto

**Comment by Wallace-Lentes** [comment]
Fiz o desafio.
Para onde eu envio o link do GitHub?
