### ISSUE TITLE
[Híbrido / SP] Flutter Developer na PILAR

### ISSUE THREAD

**Issue by alessandrosil** [Flutter-Brazil/vagas#296]
## Descrição da vaga

Estamos procurando um Frontend Engineer com experiência em desenvolvimento Flutter para se juntar à equipe da Pilar. Como um membro importante da equipe de Engenharia, você será responsável por desenvolver e manter nossos aplicativos móveis em Flutter, garantindo que eles sejam de alta qualidade e atendam às necessidades de nossos usuários.

## Local

Remoto ou Escritório, São Paulo

## Benefícios

- Gympass
- Auxílio de R$ 800,00 no Caju

## Requisitos

- Experiência com desenvolvimento Flutter;
- Conhecimentos sólidos em estruturas de dados, algoritmos, design patterns e arquitetura de sistemas;
- Experiência em boas práticas de engenharia de software, lint, testes unitários e code reviews.

## Responsabilidades:
- Desenvolver e manter nossos aplicativos móveis em Flutter;
- Trabalhar em estreita colaboração com a equipe de design para criar interfaces de usuário atraentes e fáceis de usar;
- Garantir que nossos aplicativos sejam de alta qualidade, seguros e escaláveis;
- Identificar e corrigir bugs e problemas de desempenho;
- Participar de revisões de código e fornecer feedback construtivo aos colegas de equipe;
- Manter-se atualizado sobre as tendências e tecnologias mais recentes em desenvolvimento de aplicativos móveis.

## Contratação

PJ a combinar

## Nossa empresa

https://www.soupilar.com.br/
Somos a estrutura imobiliária completa que valoriza o seu tempo e a sua profissão, com pessoas, ferramentas e tecnologia para que você possa vender mais e melhor.

## Como se candidatar

Por favor envie um email para alessandro.silva@soupilar.com.br com seu CV anexado - enviar no assunto: Vaga Flutter

**Comment by abnerdsilva** [comment]
________________________________
From: alessandrosil ***@***.***>
Sent: Tuesday, June 6, 2023 1:14:20 PM
To: flutterbr/vagas ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [flutterbr/vagas] [Cidade] Flutter Developer na PILAR (Issue #296)


Descrição da vaga

Estamos procurando um Frontend Engineer com experiência em desenvolvimento Flutter para se juntar à equipe da Pilar. Como um membro importante da equipe de Engenharia, você será responsável por desenvolver e manter nossos aplicativos móveis em Flutter, garantindo que eles sejam de alta qualidade e atendam às necessidades de nossos usuários.

Local

Remoto ou Escritório, São Paulo

Benefícios

  *   Gympass
  *   Auxílio de R$ 800,00 no Caju

Requisitos

  *   Experiência com desenvolvimento Flutter;
  *   Conhecimentos sólidos em estruturas de dados, algoritmos, design patterns e arquitetura de sistemas;
  *   Experiência em boas práticas de engenharia de software, lint, testes unitários e code reviews.

Responsabilidades:

  *   Desenvolver e manter nossos aplicativos móveis em Flutter;
  *   Trabalhar em estreita colaboração com a equipe de design para criar interfaces de usuário atraentes e fáceis de usar;
  *   Garantir que nossos aplicativos sejam de alta qualidade, seguros e escaláveis;
  *   Identificar e corrigir bugs e problemas de desempenho;
  *   Participar de revisões de código e fornecer feedback construtivo aos colegas de equipe;
  *   Manter-se atualizado sobre as tendências e tecnologias mais recentes em desenvolvimento de aplicativos móveis.

Contratação

PJ a combinar

Nossa empresa

https://www.soupilar.com.br/
Somos a estrutura imobiliária completa que valoriza o seu tempo e a sua profissão, com pessoas, ferramentas e tecnologia para que você possa vender mais e melhor.

Como se candidatar

Por favor envie um email para ***@***.******@***.***> com seu CV anexado - enviar no assunto: Vaga Flutter
