### ISSUE TITLE
[Remoto ou Híbrido] Mobile Developer Flutter Sr @RhitmoTech 💙

### ISSUE THREAD

**Issue by ghost** [Flutter-Brazil/vagas#300]
Somos a **RHITMO Tech** e aqui desenvolvemos tecnologia para pessoas! 💙

Um time que está sempre pronto para decolar e é capaz de criar e desenvolver projetos que mudam positivamente a vida das pessoas, solucionando problemas e transpondo obstáculos. Essa é a nossa missão e procuramos por talentos para compor o nosso time de tecnologia e nos apoiar nessa jornada, atuando com Desenvolvimento Flutter 📱

Quer conhecer um pouco mais sobre nós? Nossas redes sociais: 📱

https://rhitmotech.com.br/
https://www.instagram.com/rhitmotech/
https://br.linkedin.com/company/rhitmotech

## Descrição da vaga

Vamos atuar em um aplicativo na área da saúde! Então você vai:

- Buscar novas ferramentas e técnicas para a melhoria contínua de nossas soluções;
- Desenvolver e sustentar integrações;
- Realizar a manutenção e criação de novas funcionalidades;
- Aplicar melhores práticas no código desenvolvido.

## Requisitos

É necessário que você tenha:

- +3 anos de experiência em Flutter;
- Experiência em SQL
- Conhecimento em Dart;
- Conhecimento em Node ou React Native será considerado um diferencial.

## Sobre a vaga:

- Modelo de contratação: PJ
- Interrupção remunerada de 15 dias;
- Bonificação por indicação de Desenvolvedores;

## Como se candidatar

Envie o seu currículo + pretensão salárial para o e-mail: rh@rhitmo.com.br 📧

Pode se conectar comigo no linkedin também:
https://www.linkedin.com/in/mariagabrielacs/ 👩‍💻

### Nível

- Sênior;

### Regime

- PJ

### Alocação

- Remoto
- Híbrido em Belo Horizonte

**#VEMPRARHITMO!** 🚀👩‍🚀

**Comment by gabrielscr** [comment]
Olá, enviei no e-mail meu currículo!
