### ISSUE TITLE
[100% remoto] Flutter Developer na nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [Flutter-Brazil/vagas#313]
## Descrição da vaga

Atuar no desenvolvimento, sustentação, manutenção, monitoria e documentação dos sistemas;
· Participar dos desenhos de padrões de arquitetura e soluções de melhoria para os projetos.

## Local

100% remoto

## Requisitos
Necessário:
· Desenvolvimento em Flutter como linguagem principal e Nativo (Android ou IOS);
· Git;
· Design Patterns: MVVM e Clean Architecture;
· Guidelines (Material Design);
· Json;
· Rest;
· Kanban.

**Desejáveis:**
Fluência com Git Flow
· Retrofit
· Scrum
· Programação Reativa
· Java e Kotlin (ou) Swift
· .Net

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para helen.matos@nexmuv.com.br  com seu CV anexado - enviar no assunto: Vaga Flutter

## Labels

- PJ
- Pleno
- Remoto
- Sênior

**Comment by matiasdev30** [comment]
Olá sou Desenvolvedor Flutter com mais de 4 anos de experiencia no mercado

**Comment by igormidev** [comment]
Fala amigo, tudo certo? Parece ter uma oportunidade de ótima parceria aqui.

Eu programo em flutter desde o beta. Antes mesmo da versão 1.0 ser lançada.
Nesse tempo eu criei 6 packages open source para a comunidade.
Também já trabalhei em aplicativo com mais de 500 mil usuários e como tech lead de um banco (aplicativo que mexe com dinheiro das pessoas)

Inclusive, tenho um site curriculo feito em flutter.
O link:
https://igorcurriculum.com/
![image](https://github.com/flutterbr/vagas/assets/97634286/02f496c2-84f8-4826-85bc-61652f086f0e)

**Comment by matiasdev30** [comment]
Sim Igor, mais eu também sou desenvolvedor Flutter, com mais de 4 anos de
experiência no mercado

Tenho um package não no pub.dev, open source também.

E já liderei um team também, e tenho um portfólio feito em Flutter Web na
altura que fiz ainda estava em beta, ainda não atualizei até aqui, mais da
para dar uma olhada
https://matiasdev30.github.io/

igormidev ***@***.***> escreveu (quinta, 18/01/2024 à(s)
21:52):

**Comment by eduardohr-muniz** [comment]
Olá gostaria de expressar meu interesse na vaga, vou adicionar meu curricullum em anexo e linkedin, pelos requisitos da vaga creio que eu vá somar muito com o time.
[Curriculum Eduardo Flutter.pdf](https://github.com/flutterbr/vagas/files/14142055/Curriculum.Eduardo.Flutter.pdf)
https://www.linkedin.com/in/eduardohrmuniz/
