### ISSUE TITLE
[REMOTO] Flutter Developer Pleno na 1ncrivel Sistemas

### ISSUE THREAD

**Issue by thomasgan** [Flutter-Brazil/vagas#317]
**Nossa Empresa**
Na 1ncrivel Sistemas, uma software house inovadora, valorizamos a criatividade, a colaboração e o compromisso com a excelência. Trabalhamos em uma variedade de projetos desafiadores, com o objetivo de sempre oferecer a melhor solução tecnológicas aos problemas de nossos clientes. Estamos em constante busca por talentos que possam contribuir para nossa jornada de crescimento e sucesso.

**Descrição da Vaga**
Estamos procurando um Desenvolvedor Flutter Pleno, experiente e autossuficiente, capaz de gerenciar projetos de desenvolvimento de forma independente. O candidato ideal será responsável por:

**Responsabilidades**
	- Desenvolver interfaces de usuário utilizando Flutter
	- Implementar lógica de negócio no back-end usando PHP
	- Colaborar com designers e desenvolvedores para implementar recursos e melhorias
	- Realizar integração de APIs e serviços externos (Gateways de pagamentos, entre outros...)
	- Garantir a segurança e eficiência das aplicações
	- Identificar e resolver problemas de desempenho e escalabilidade
	- Participar de revisões de código e testes 
	
	
**Requisitos**
	- Experiência superior a 3 anos comprovada com PHP;
	- Experiência comprovada em desenvolvimento Flutter
	- Experiência em desenvolvimento de APIs RESTful;
	- Experiência com ferramentas de controle de versões (GIT);
	- Familiaridade com bancos de dados não relacionais (por exemplo, MongoDB, Redis);
	- Familiaridade com bancos de dados relacionais (por exemplo, MySQL);
	- Experiência em testes unitários e integração contínua;
	- Experiência com Docker;
	- Conhecimento de práticas de segurança web e proteção contra vulnerabilidades;
	- Familiaridade com metodologias ágeis de desenvolvimento, como Scrum ou Kanban;

**Diferenciais**
	- Servidores Linux
	- Mensageria (SQS, RabbitMQ)
	- Wordpress
	- Docker
	- GCP
	- Web Crawlers
	
**Local**
- Remoto

**Benefícios**
- Bônus por contratação.

**Regime**
- PJ

**Como se Candidatar**
Envie seu currículo e carta de apresentação para [thomas@nptunnel.com](mailto:thomas@nptunnel.com), com o assunto "Candidatura - Desenvolvedor Flutter Developer Pleno".

**Comment by ThallesVicenzo** [comment]
Olá, enviei minha candidatura

**Comment by iagognunes** [comment]
Bom dia, enviei a minha candidatura.

**Comment by Augustob790** [comment]
Bom dia, enviei minha candidatura.
