### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Mobile Sênior

### ISSUE THREAD

**Issue by GabrielRozendo** [Flutter-Brazil/vagas#6]
Vaga para desenvolvedor mobile sênior, que queira conhecer e trabalhar com Flutter em BH.
Mesmo sem experiência em Flutter

Dúvidas e detalhes da vaga procurar o Fabrício: 
fabricio.pereira@levelexec.com.br 
(21) 989210414

**Comment by zeucxb** [comment]
Pq escolheu não seguir o template? Teve algum problema com ele?

**Comment by Gui-S** [comment]
Boa tarde Eliseu,

Achei que tivesse seguido o template.
Se possível, gostaria de saber qual foi esse problema e como posso
consertá-lo.

Obrigado.

Em ter., 5 de nov. de 2019 às 11:07, Eliseu Codinhoto <
notifications@github.com> escreveu:
